#!/usr/bin/env python3
"""Render / export: markdown as a GENERATED artifact, not truth.

This is the load-bearing constraint of the whole proposal (§4.1.2). If markdown is
generated, then it must be:

  R1  deterministic  -- same DB state renders byte-identical output, twice
  R2  self-consistent -- every count it states equals the data it lists
  R3  complete       -- a human (or an agent with no Dolt) can read the whole corpus
  R4  round-trippable -- re-importing the render reproduces the same records
  R5  diff-friendly  -- a one-field change produces a SMALL diff, so PR review survives
  R6  drift-detecting -- a hand-edit of a generated file is caught, not silently kept
  R7  fast enough    -- rendering the whole corpus is not a coffee break

Run: .venv/bin/python -u poc/test_render.py
"""
from __future__ import annotations

import hashlib
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pymysql

PORT, DB = 3308, "factory_artifacts"
OUT = Path("poc/rendered_test")
RESULTS: list[tuple[str, bool, str]] = []


def conn(autocommit=True):
    return pymysql.connect(host="127.0.0.1", port=PORT, user="root", database=DB,
                           autocommit=autocommit, cursorclass=pymysql.cursors.DictCursor)


def q(c, sql, args=None):
    with c.cursor() as cur:
        cur.execute(sql, args or ())
        try:
            return cur.fetchall()
        except Exception:
            return []


def check(name, ok, detail=""):
    RESULTS.append((name, ok, detail))
    print(f"{'PASS' if ok else 'FAIL'}  {name}")
    for ln in (detail or "").splitlines():
        print(f"        {ln}")


# ------------------------------------------------------------------ renderer


HEADER = "<!-- GENERATED by `datum render`. DO NOT EDIT. Source of truth is the DB. -->"


def render_all(out: Path) -> dict[str, str]:
    """Render the full corpus: one file per BC plus a generated index.

    Ordering is fully deterministic (ORDER BY on every query) — otherwise the export
    churns on every run and the git diff becomes useless.
    """
    c = conn()
    if out.exists():
        shutil.rmtree(out)
    (out / "behavioral-contracts").mkdir(parents=True)
    written: dict[str, str] = {}

    bcs = q(c, """SELECT bc_id, ss_id, title, body, capability, version, lifecycle_status
                  FROM bc ORDER BY bc_id""")
    for r in bcs:
        lines = [
            "---",
            f"bc_id: {r['bc_id']}",
            f"subsystem: {r['ss_id']}",
            f"capability: {r['capability'] or ''}",
            f"version: {r['version']}",
            f"lifecycle_status: {r['lifecycle_status'] or 'active'}",
            "generated: true",
            "---",
            HEADER,
            "",
            f"# {r['bc_id']}: {r['title']}",
            "",
            (r["body"] or "").rstrip(),
            "",
        ]
        p = out / "behavioral-contracts" / f"{r['bc_id']}.md"
        txt = "\n".join(lines)
        p.write_text(txt)
        written[str(p.relative_to(out))] = txt

    per_ss = q(c, """SELECT s.ss_id, s.name, COUNT(b.bc_id) n
                     FROM subsystem s LEFT JOIN bc b ON b.ss_id=s.ss_id
                     GROUP BY s.ss_id, s.name ORDER BY s.ss_id""")
    total = len(bcs)
    idx = ["---", "document_type: bc-index", "generated: true",
           f"total_bcs: {total}", "---", HEADER, "",
           "# BC-INDEX", "", f"Total BCs: {total}", "",
           "| Subsystem | Name | Count |", "|---|---|---|"]
    for r in per_ss:
        idx.append(f"| {r['ss_id']} | {r['name']} | {r['n']} |")
    idx += [f"| **Total** | | **{total}** |", "",
            "| BC | Subsystem | Capability | Version | Title |", "|---|---|---|---|---|"]
    for r in bcs:
        t = str(r["title"]).replace("|", "\\|")[:120]
        idx.append(f"| {r['bc_id']} | {r['ss_id']} | {r['capability'] or 'TBD'} "
                   f"| {r['version']} | {t} |")
    p = out / "behavioral-contracts" / "BC-INDEX.md"
    txt = "\n".join(idx) + "\n"
    p.write_text(txt)
    written[str(p.relative_to(out))] = txt
    c.close()
    return written


def parse_fm(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    out = {}
    for ln in m.group(1).splitlines():
        if ":" in ln:
            k, _, v = ln.partition(":")
            out[k.strip()] = v.strip()
    return out


def digest(files: dict[str, str]) -> str:
    h = hashlib.sha256()
    for k in sorted(files):
        h.update(k.encode())
        h.update(files[k].encode())
    return h.hexdigest()[:16]


# ---------------------------------------------------------------- tests


def r1_deterministic():
    t0 = time.time()
    a = render_all(OUT)
    dt1 = time.time() - t0
    da = digest(a)
    b = render_all(OUT)
    db_ = digest(b)
    check("R1 render is deterministic: two runs are byte-identical",
          da == db_ and len(a) == len(b),
          f"{len(a)} files; digest run1={da} run2={db_} identical={da == db_}\n"
          f"first render took {dt1:.1f}s\n"
          "=> every query is ORDER BY'd; without that the export churns each run and\n"
          "   the git diff becomes unreadable noise")


def r2_self_consistent():
    files = render_all(OUT)
    idx = files["behavioral-contracts/BC-INDEX.md"]
    fm = int(parse_fm(idx)["total_bcs"])
    body = int(re.search(r"\|\s*\*\*Total\*\*\s*\|[^|]*\|\s*\*\*(\d+)\*\*", idx).group(1))
    stated = int(re.search(r"^Total BCs:\s*(\d+)", idx, re.M).group(1))
    listed = len(set(re.findall(r"^\| (BC-\d+\.\d+\.\d+) \|", idx, re.M)))
    per_file = len([k for k in files if k.startswith("behavioral-contracts/BC-")
                    and not k.endswith("BC-INDEX.md")])
    c = conn()
    dbn = q(c, "SELECT COUNT(*) n FROM bc")[0]["n"]
    c.close()
    vals = {fm, body, stated, listed, per_file, dbn}
    check("R2 every count in the render equals the data it lists",
          len(vals) == 1,
          f"frontmatter total_bcs = {fm}\nprose 'Total BCs' = {stated}\n"
          f"table **Total** row  = {body}\nindex rows listed    = {listed}\n"
          f"per-BC files written = {per_file}\nDB COUNT(*)          = {dbn}\n"
          f"distinct values = {sorted(vals)} (want exactly 1)\n"
          "=> contrast the live corpus, which states FOUR different totals (§1.2)")


def r3_complete_without_dolt():
    """A reader with no Dolt must be able to reconstruct the corpus. Check that every
    DB record appears as a readable file with its identifying fields."""
    files = render_all(OUT)
    c = conn()
    rows = q(c, "SELECT bc_id, ss_id, version FROM bc ORDER BY bc_id")
    c.close()
    missing, wrong = [], []
    for r in rows:
        key = f"behavioral-contracts/{r['bc_id']}.md"
        if key not in files:
            missing.append(r["bc_id"])
            continue
        fm = parse_fm(files[key])
        if fm.get("subsystem") != r["ss_id"] or fm.get("version") != r["version"]:
            wrong.append(r["bc_id"])
    check("R3 export is complete: every record is a readable file with its fields",
          not missing and not wrong,
          f"{len(rows)} records -> {len(files) - 1} per-record files + 1 index\n"
          f"missing files: {len(missing)}; field mismatches: {len(wrong)}\n"
          "=> this doubles as the disaster-recovery fallback: plain markdown in git,\n"
          "   readable with no tooling at all")


def r4_round_trip():
    """Re-importing the render must reproduce the same records. If it cannot, the
    export is lossy and cannot be the human-facing representation."""
    files = render_all(OUT)
    c = conn()
    before = {r["bc_id"]: (r["ss_id"], r["version"], r["capability"], r["title"])
              for r in q(c, "SELECT bc_id, ss_id, version, capability, title FROM bc")}
    c.close()
    reparsed = {}
    for k, txt in files.items():
        if not k.startswith("behavioral-contracts/BC-") or k.endswith("BC-INDEX.md"):
            continue
        fm = parse_fm(txt)
        m = re.search(r"^# (BC-\d+\.\d+\.\d+): (.*)$", txt, re.M)
        if not m:
            continue
        reparsed[fm["bc_id"]] = (fm["subsystem"], fm["version"],
                                 fm["capability"] or None, m.group(2))
    same_ids = set(before) == set(reparsed)
    diffs = [k for k in before if k in reparsed and before[k] != reparsed[k]]
    check("R4 round-trip: parsing the render back reproduces the same records",
          same_ids and not diffs,
          f"records in DB={len(before)}, recovered from render={len(reparsed)}, "
          f"id sets equal={same_ids}\nfield-level mismatches={len(diffs)}"
          + (f"\n  e.g. {diffs[0]}: db={before[diffs[0]]} render={reparsed[diffs[0]]}"
             if diffs else "")
          + "\n=> the render is lossless for the fields it carries, so it is safe to\n"
            "   treat markdown as a view rather than a second source of truth")


def r5_small_diff():
    """A one-field change must produce a SMALL diff. If a single edit rewrites the
    whole corpus, PR review dies."""
    render_all(OUT)
    base = Path("poc/_r5_base")
    if base.exists():
        shutil.rmtree(base)
    shutil.copytree(OUT, base)
    c = conn()
    bc = q(c, "SELECT bc_id FROM bc ORDER BY bc_id LIMIT 1")[0]["bc_id"]
    old = q(c, "SELECT capability FROM bc WHERE bc_id=%s", (bc,))[0]["capability"]
    q(c, "UPDATE bc SET capability='CAP-999' WHERE bc_id=%s", (bc,))
    c.close()
    render_all(OUT)
    d = subprocess.run(["diff", "-rq", str(base), str(OUT)], capture_output=True, text=True)
    changed = [l for l in (d.stdout or "").splitlines() if l.strip()]
    d2 = subprocess.run(["diff", "-r", str(base), str(OUT)], capture_output=True, text=True)
    changed_lines = len([l for l in (d2.stdout or "").splitlines()
                         if l.startswith(("<", ">"))])
    c = conn()
    q(c, "UPDATE bc SET capability=%s WHERE bc_id=%s", (old, bc))
    c.close()
    shutil.rmtree(base)
    check("R5 a one-field change touches only that record + the index",
          len(changed) == 2 and changed_lines <= 8,
          f"changed {bc}.capability -> CAP-999\n"
          f"files differing: {len(changed)} (want 2: the record and the index)\n"
          + "".join(f"  {l}\n" for l in changed[:4])
          + f"changed lines total: {changed_lines}\n"
          "=> per-record files keep diffs proportional to the change; a single\n"
            "   monolithic index file would rewrite on every edit")


def r6_detect_hand_edit():
    """Someone WILL hand-edit a generated file. That must be detected, not silently
    honoured or silently discarded."""
    files = render_all(OUT)
    target = OUT / "behavioral-contracts" / sorted(
        k for k in files if k.endswith(".md") and not k.endswith("BC-INDEX.md"))[0].split("/")[-1]
    original = target.read_text()
    target.write_text(original.replace("# BC-", "# HANDEDITED BC-", 1))
    # fa's check: re-render to a temp location and compare.
    fresh = render_all(Path("poc/_r6_fresh"))
    rel = str(target.relative_to(OUT))
    drifted = fresh[rel] != target.read_text()
    has_marker = HEADER in original
    shutil.rmtree(Path("poc/_r6_fresh"))
    render_all(OUT)                                  # restore
    check("R6 a hand-edit of a generated file is detected",
          drifted and has_marker,
          f"hand-edited {rel}\n"
          f"re-render differs from the file on disk = {drifted}\n"
          f"file carries a DO-NOT-EDIT marker = {has_marker}\n"
          "=> `datum render --check` (re-render + compare) is a CI gate. Without it the\n"
            "   edit is silently lost on the next render, which is the worst outcome")


def r7_render_cost():
    t0 = time.time()
    files = render_all(OUT)
    dt = time.time() - t0
    total_bytes = sum(len(v) for v in files.values())
    check("R7 rendering the whole corpus is cheap enough to do on every commit",
          dt < 60,
          f"{len(files)} files, {total_bytes/1e6:.1f} MB in {dt:.1f}s "
          f"({1000*dt/max(1,len(files)):.1f} ms/file)")


def main():
    print("=" * 74)
    print("Render / export — markdown as a GENERATED artifact")
    print("=" * 74)
    for t in (r1_deterministic, r2_self_consistent, r3_complete_without_dolt,
              r4_round_trip, r5_small_diff, r6_detect_hand_edit, r7_render_cost):
        try:
            t()
        except Exception:
            import traceback
            check(f"{t.__name__} (ERROR)", False, traceback.format_exc()[-600:])
        print()
    if OUT.exists():
        shutil.rmtree(OUT)
    n = sum(1 for _, ok, _ in RESULTS if ok)
    print("=" * 74)
    print(f"{n}/{len(RESULTS)} passed")
    for nm, ok, _ in RESULTS:
        if not ok:
            print(f"  FAILED: {nm}")
    sys.exit(0 if n == len(RESULTS) else 1)


if __name__ == "__main__":
    main()
