package main

// The dated baseline allowlist.
//
// DECISIONS D3: "`fa validate` finds 38 dangling references and 44 type violations
// in the corpus today. A gate with no baseline therefore blocks every PR on day
// one and will be switched off within a day."
//
// So the baseline is not a convenience — it is the difference between a gate that
// survives and a gate that gets disabled. Three properties make it work:
//
//   1. It is ITEMISED. Every tolerated finding is named, so nobody can hide a new
//      violation inside a tolerated total.
//   2. It is DATED and attributed to a corpus commit, so "we accepted this" has a
//      when and a what.
//   3. It RATCHETS. New findings fail. Fixed findings are reported as removable.
//      The tolerated set can only shrink, and `fa validate --strict` ignores it
//      entirely.

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

const baselineNote = "Generated by `fa baseline write`. Tolerated findings only shrink: " +
	"new findings fail the gate, fixed ones are reported for removal. `fa validate --strict` ignores this file."

type BaselineEntry struct {
	Rule    string `json:"rule"`
	Subject string `json:"subject"`
	Class   string `json:"class"`
	// Waiver records WHY a finding is still tolerated. D3's exit criterion into
	// phase 2 is "the baseline is at zero, or each remaining item is explicitly
	// waived with a reason" — this field is where that reason lives.
	Waiver string `json:"waiver,omitempty"`
}

type Baseline struct {
	Note        string          `json:"note"`
	Generated   string          `json:"generated"`
	FaVersion   string          `json:"fa_version"`
	CorpusPath  string          `json:"corpus_path,omitempty"`
	CorpusRef   string          `json:"corpus_ref,omitempty"`
	Fingerprint string          `json:"corpus_fingerprint,omitempty"`
	Counts      map[string]int  `json:"counts"`
	Findings    []BaselineEntry `json:"findings"`
}

func key(rule, subject string) string { return rule + "\x00" + subject }

func (b *Baseline) index() map[string]BaselineEntry {
	m := make(map[string]BaselineEntry, len(b.Findings))
	for _, e := range b.Findings {
		m[key(e.Rule, e.Subject)] = e
	}
	return m
}

// NewBaseline builds a baseline from a validation report.
func NewBaseline(rep *Report, date, corpusPath, corpusRef, fingerprint string, prev *Baseline) *Baseline {
	b := &Baseline{
		Note: baselineNote, Generated: date, FaVersion: faVersion,
		CorpusPath: corpusPath, CorpusRef: corpusRef, Fingerprint: fingerprint,
		Counts: map[string]int{"total": len(rep.Findings)},
	}
	for cls, n := range ByClass(rep.Findings) {
		b.Counts[cls] = n
	}
	// Carry forward any waiver text already written by a human: regenerating the
	// baseline must not silently discard the reasons someone recorded.
	var carried map[string]BaselineEntry
	if prev != nil {
		carried = prev.index()
	}
	for _, f := range rep.Findings {
		e := BaselineEntry{Rule: f.Rule, Subject: f.Subject, Class: f.Class}
		if old, ok := carried[key(f.Rule, f.Subject)]; ok {
			e.Waiver = old.Waiver
		}
		b.Findings = append(b.Findings, e)
	}
	sort.Slice(b.Findings, func(i, j int) bool {
		a, c := b.Findings[i], b.Findings[j]
		if a.Class != c.Class {
			return a.Class < c.Class
		}
		if a.Rule != c.Rule {
			return a.Rule < c.Rule
		}
		return a.Subject < c.Subject
	})
	return b
}

func LoadBaseline(path string) (*Baseline, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var b Baseline
	dec := json.NewDecoder(f)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&b); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &b, nil
}

func (b *Baseline) Save(path string) error {
	data, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

type Diff struct {
	New   []Finding       // present now, not tolerated -> the gate fails
	Fixed []BaselineEntry // tolerated, no longer present -> ratchet the baseline down
	Kept  []Finding       // tolerated and still present
}

// Compare diffs a report against a baseline. A nil baseline means everything is new.
func Compare(rep *Report, b *Baseline) Diff {
	var d Diff
	if b == nil {
		d.New = append(d.New, rep.Findings...)
		return d
	}
	tolerated := b.index()
	seen := map[string]bool{}
	for _, f := range rep.Findings {
		k := key(f.Rule, f.Subject)
		seen[k] = true
		if _, ok := tolerated[k]; ok {
			d.Kept = append(d.Kept, f)
		} else {
			d.New = append(d.New, f)
		}
	}
	for _, e := range b.Findings {
		if !seen[key(e.Rule, e.Subject)] {
			d.Fixed = append(d.Fixed, e)
		}
	}
	sort.Slice(d.Fixed, func(i, j int) bool {
		if d.Fixed[i].Rule != d.Fixed[j].Rule {
			return d.Fixed[i].Rule < d.Fixed[j].Rule
		}
		return d.Fixed[i].Subject < d.Fixed[j].Subject
	})
	return d
}

// PrintReport writes the human-readable result. The verdict is DERIVED from the
// numbers at print time and never pre-written into the text — a report that states
// a conclusion its own numbers contradict is worse than no report.
func PrintReport(w io.Writer, rep *Report, b *Baseline, d Diff, strict bool) {
	fmt.Fprintf(w, "records   bc=%d vp=%d story=%d subsystem=%d edges=%d\n",
		rep.Metrics["bc"], rep.Metrics["vp"], rep.Metrics["story"],
		rep.Metrics["subsystem"], rep.Metrics["edges"])
	fmt.Fprintf(w, "coverage  BCs with no verifying VP: %d/%d (%.1f%%)  BCs with no story: %d\n",
		rep.Metrics["bc_without_vp"], rep.Metrics["bc"],
		pct(rep.Metrics["bc_without_vp"], rep.Metrics["bc"]), rep.Metrics["bc_without_story"])
	if rep.CrossZoneChecked {
		fmt.Fprintf(w, "cross-zone  checked, %d walled->open reference(s)\n", rep.Metrics["cross_zone_refs"])
	} else {
		fmt.Fprintf(w, "cross-zone  SKIPPED (%s) — not a pass\n", rep.CrossZoneSkipped)
	}

	fmt.Fprintf(w, "\nfindings  %d total", len(rep.Findings))
	if cls := ByClass(rep.Findings); len(cls) > 0 {
		keys := make([]string, 0, len(cls))
		for k := range cls {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var parts []string
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%s=%d", k, cls[k]))
		}
		fmt.Fprintf(w, "  (%s)", strings.Join(parts, " "))
	}
	fmt.Fprintln(w)
	for _, r := range ByRule(rep.Findings) {
		fmt.Fprintf(w, "  %5d  %-12s %s\n", r.N, r.Class, r.Rule)
	}

	if b == nil {
		fmt.Fprintf(w, "\nbaseline  NONE — every finding is treated as new\n")
	} else {
		fmt.Fprintf(w, "\nbaseline  %s (%d tolerated, corpus %s)\n",
			b.Generated, len(b.Findings), shortRef(b.CorpusRef))
		waived := 0
		for _, e := range b.Findings {
			if e.Waiver != "" {
				waived++
			}
		}
		fmt.Fprintf(w, "          kept=%d fixed=%d new=%d waived=%d\n",
			len(d.Kept), len(d.Fixed), len(d.New), waived)
	}

	if len(d.Fixed) > 0 {
		fmt.Fprintf(w, "\nFIXED since the baseline (%d) — run `fa baseline write` to ratchet down:\n", len(d.Fixed))
		for _, e := range d.Fixed[:min(len(d.Fixed), 20)] {
			fmt.Fprintf(w, "  - [%s] %s :: %s\n", e.Class, e.Rule, e.Subject)
		}
		if len(d.Fixed) > 20 {
			fmt.Fprintf(w, "  ... and %d more\n", len(d.Fixed)-20)
		}
	}

	if len(d.New) > 0 {
		fmt.Fprintf(w, "\nNEW findings (%d) — these fail the gate:\n", len(d.New))
		for _, f := range d.New {
			fmt.Fprintf(w, "  FAIL [%s] %s :: %s", f.Class, f.Rule, f.Subject)
			if f.Detail != "" {
				fmt.Fprintf(w, "  (%s)", f.Detail)
			}
			fmt.Fprintln(w)
		}
	}

	switch {
	case strict && len(rep.Findings) > 0:
		fmt.Fprintf(w, "\nFAIL  --strict: %d finding(s), baseline ignored\n", len(rep.Findings))
	case len(d.New) > 0:
		fmt.Fprintf(w, "\nFAIL  %d new finding(s) beyond the baseline\n", len(d.New))
	case len(rep.Findings) > 0:
		fmt.Fprintf(w, "\nPASS  no new findings (%d baselined finding(s) remain)\n", len(rep.Findings))
	default:
		fmt.Fprintln(w, "\nPASS  no findings")
	}
}

func pct(a, b int64) float64 {
	if b == 0 {
		return 0
	}
	return 100 * float64(a) / float64(b)
}

func shortRef(r string) string {
	if r == "" {
		return "unknown"
	}
	return truncRunes(r, 12)
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
